# Generated by Django 5.0.3 on 2024-08-03 04:03

import escola.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[escola.validators.validate_cpf]),
        ),
    ]
