# Generated by Django 5.0.3 on 2024-08-05 22:55

import escola.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_alter_curso_options_alter_estudante_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='celular',
            field=models.CharField(max_length=14, validators=[escola.validators.validate_celular]),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='nome',
            field=models.CharField(max_length=100, validators=[escola.validators.validate_nome]),
        ),
    ]
